AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - web_pipe.gemspec

Naming/AccessorMethodName:
  Enabled: false

Style/HashConversion:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/LambdaCall:
  EnforcedStyle: braces
