AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/AccessorMethodName:
  Enabled: false

Style/HashConversion:
  Enabled: false
